### PR TITLE
🐛 Fixed keyboard navigation when menuSection is present

### LINKED ISSUE #1668: Menu Item onClick not running correctly in scrolling container
**Describe the bug**

Clicking `Menu.Item` doesn't run onClick event as expected when dynamically creating Menu component with max-height and overflow: auto.

**Steps to reproduce the bug**

1. Create Menu component with `overflow: auto` and `max-height: 'some-value'`
2. Create Menu.Item's inside Menu.Section(s) (same bug appears if all the items are in the same section) 
3. Click Menu.Item
4. Menu scrolls to bottom instead of running onClick

**Expected behavior**

Clicking Menu.Item's inside Menu.Section's which are in turn inside a styled Menu-component with max-height and overflow should just run onClick event and not scroll to bottom on first click.

**Specifications**

- Version: 0.14.2
- Browser: Chrome 95.0.4638.54
- OS: macOS

**Additional context**

Codesandbox: [https://codesandbox.io/s/focused-wind-7flk0?file=/src/App.js](https://codesandbox.io/s/focused-wind-7flk0?file=/src/App.js)

Video:

https://user-images.githubusercontent.com/24507952/139652458-0fc5e07b-124f-4eb5-982b-66fa7e2fdaea.mov

u

### PR DESCRIPTION
**Pull request by oddvernes**
Resolves #1668 

The internal logic to add indexes to focusable children and then make them focusable with keyboard did not work at all with menuSections present. 
I have changed the code now to add index to menuItems inside sections, as well as menuItems that are not in sections. I then  made a separate flat array of children to build the focusableIndexs.

I also added event.preventDefault when pressing up/down arrows inside menu to stop scrolling the viewport.

On a sidenote it does not appear that memo works on menuItems, I guess because of the function props, so there are probably some more optimizations that can be done on this component

### CODE REVIEW

**Review by mimarz — CHANGES_REQUESTED** [review]

File: libraries/core-react/src/components/Menu/MenuList.tsx [hunk 1]
```diff
@@ -45,17 +37,38 @@ export const MenuList = forwardRef<HTMLUListElement, MenuListProps>(
...
+          )
+          return cloneElement(child as MenuChild, null, updatedGrandChildren)
+        } else {
+          index++
+          return cloneElement(child as MenuChild, { index })
+        }
+      },
+    )
+
+    const flattenedChildren = ReactChildren.map(
```
Comment (mimarz) [inline libraries/core-react/src/components/Menu/MenuList.tsx:60]: Memo?

File: libraries/core-react/src/components/Menu/MenuList.tsx [hunk 2]
```diff
@@ -45,17 +37,38 @@ export const MenuList = forwardRef<HTMLUListElement, MenuListProps>(
...
-
+    let index = -1
     const updatedChildren: Array<MenuChild> = ReactChildren.map(
-      pickedChildren,
-      (child: ReactNode, index: number) =>
-        cloneElement(child as MenuChild, { index }),
+      children,
+      (child: ReactNode) => {
+        if ((child as MenuChild).type === MenuSection) {
+          const updatedGrandChildren = ReactChildren.map(
```
[the remark this answers is not in the document]
Comment (oddvernes) [reply libraries/core-react/src/components/Menu/MenuList.tsx:53]: Since i need the original structure to pass on as children, I changed this to build the indexable list directly in the first loop instead.

File: libraries/core-react/src/components/Menu/MenuList.tsx (hunk 1 above)
Comment (oddvernes) [reply libraries/core-react/src/components/Menu/MenuList.tsx]: got rid of flattenedChildren entirely

File: libraries/core-react/src/components/Menu/MenuList.tsx [hunk 3]
```diff
@@ -45,17 +37,38 @@ export const MenuList = forwardRef<HTMLUListElement, MenuListProps>(
   function MenuList({ children, focus, ...rest }, ref) {
     const { focusedIndex, setFocusedIndex } = useMenu()
 
-    const pickedChildren = isFragment(children)
-      ? (children as MenuChild).props.children
-      : children
-
+    let index = -1
     const updatedChildren: Array<MenuChild> = ReactChildren.map(
```
[the remark this answers is not in the document]
Comment (oddvernes) [reply libraries/core-react/src/components/Menu/MenuList.tsx:49]: I'll try this

[the remark this answers is not in the document]
Comment (oddvernes) [reply libraries/core-react/src/components/Menu/MenuList.tsx]: I added useMemo and now updatedChildren is only run when menu is opened and closed but not during scrolling as it did before

File: libraries/core-react/src/components/Menu/MenuList.tsx [hunk 4]
```diff
@@ -41,28 +34,41 @@ type MenuChild = ReactElement<MenuItemProps> & ReactElement<MenuSectionProps>
...
-    const pickedChildren = isFragment(children)
-      ? (children as MenuChild).props.children
-      : children
-
-    const updatedChildren: Array<MenuChild> = ReactChildren.map(
-      pickedChildren,
-      (child: ReactNode, index: number) =>
-        cloneElement(child as MenuChild, { index }),
+    let index = -1
+    const focusableIndexs: number[] = useMemo<number[]>(() => [], [])
```
Comment (mimarz) [inline libraries/core-react/src/components/Menu/MenuList.tsx:48]: Just curious, whats the benefit of putting memonizing this constant when is used from a memonized function?

**Review by mimarz — APPROVED** [review]
LGTM 👍

Its almost as if we could extract some of logic to a seperate hook later to fulfil #1186
`focusableIndexs` could have lived inside the react context in a hook/provider 🤔

File: libraries/core-react/src/components/Menu/MenuList.tsx (hunk 4 above)
Comment (oddvernes) [reply libraries/core-react/src/components/Menu/MenuList.tsx:48]: The linter told me to do it:
`The 'focusableIndexs' array makes the dependencies of useMemo Hook (at line 70) change on every render. To fix this, wrap the initialization of 'focusableIndexs' in its own useMemo() Hook.`

Comment (mimarz) [reply libraries/core-react/src/components/Menu/MenuList.tsx:48]: aha, probably because its declared in the function, which means that it would be re-declared on every render 🤔
