### PR TITLE
Split fullWidth Button and regular Button

### LINKED ISSUE #1364: Wrong empty spaces in Button when an icon is used
When we introduced `fullWidth` we had to do some trickery internally with `flex` & `margins` to get icons to float out to the sides. This introduces some unwanted conseques with large empty spaces in our "normal" `Button` when using an `Icon` on one side. We thought we could live with it but we can't!

Design in [Figma](https://www.figma.com/file/0bGXR2sCwMVSDNyyzu5BXrO5/UI%E2%80%94User-Interface?node-id=17394%3A47297)

Actions
* We should introduce a separate "clone" of `Button` called `ButtonFullWidth` (or something like that) which we use instead when property `fullWidth` is set. This will lets us contain the h4xory for floating icons to the sides 🙈

### PR DESCRIPTION
**Pull request by pomfrida**
Resolves #1364

### CODE REVIEW

File: libraries/core-react/src/components/Button/ButtonFullWidth.tsx [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+  > span:only-child {
+    margin-right: 0;
+    margin-left: 0;
+  }
+`
+
+export const ButtonFullWidth = forwardRef<
+  HTMLSpanElement,
+  HTMLAttributes<HTMLSpanElement>
+>(function ButtonFullWidth({ children, ...other }, ref) {
```
Comment (mimarz) [inline libraries/core-react/src/components/Button/ButtonFullWidth.tsx:47]: Remove unused parameters

**Review by mimarz — APPROVED** [review]
LGTM 👍
