### PR TITLE
Use component src in the Storybook

### LINKED ISSUE #721: Docgen info not generated for typescript components
**Describe the bug**

**Steps to reproduce the bug**

1. Rewrite a component in typescript
2. Run build:for-storybook

**Expected behavior**

The bundle should have a docgen object for each component

### PR DESCRIPTION
**Pull request by vnys**
part of solving #721 

I’ve disabled the `displayName` in most of the components, but _some_ components explisitly require it according to Eslint – I have not looked into why at this point. I suggest merging this in, and then as a next step start debugging why some components are missing props. 

There’s a new way of documenting arguments with controls similar to addon-knobs, see the <Divider /> for an example of how this works, or read the section on [args in the docs](https://storybook.js.org/docs/react/writing-stories/args). 

To write a story in typescript, just change the suffix to `tsx`. Again see the Divider story for an example. 

Note that dockerizing the Storybook does not work at the moment and will have to be fixed before merging the typescript branch into develop

### CODE REVIEW

File: apps/storybook-react/.storybook/main.js [hunk 1]
```diff
@@ -1,5 +1,11 @@
 module.exports = {
-  stories: ['../docs/**/*.story.mdx', '../stories/**/*.stor(y|ies).(jsx|mdx)'],
+  // typescript: {
+  //   reactDocgen: 'react-docgen',
+  // },
```
Comment (vnys) [inline apps/storybook-react/.storybook/main.js:4]: Leaving this as a reminder. Storybook will move to `react-docgen` in v7.0

File: apps/storybook-react/.storybook/main.js [hunk 2]
```diff
@@ -1,5 +1,11 @@
...
+  stories: [
+    '../docs/**/*.story.mdx',
+    '../stories/**/*.stor(y|ies).(jsx|mdx|tsx)',
```
Comment (vnys) [inline apps/storybook-react/.storybook/main.js:7]: Adding `tsx`, assuming we won’t need `ts` too.

File: libraries/core-react/package.json [hunk 3]
```diff
@@ -81,6 +84,7 @@
     "@equinor/eds-tokens": "workspace:*",
     "@testing-library/react-hooks": "^3.3.0",
     "@types/lodash": "^4.14.162",
+    "babel-plugin-react-docgen-typescript": "^1.5.1",
```
Comment (vnys) [inline libraries/core-react/package.json:87]: this should be removed

File: libraries/core-react/src/Popover/PopoverAnchor.tsx [hunk 4]
```diff
@@ -12,4 +12,4 @@ export const PopoverAnchor = forwardRef<HTMLDivElement, Props>(
   },
 )
 
-PopoverAnchor.displayName = 'eds-popover-anchor'
+// PopoverAnchor.displayName = 'eds-popover-anchor'
```
Comment (pomfrida) [inline libraries/core-react/src/Popover/PopoverAnchor.tsx:15]: Remove comment, this `displayName` is needed in `Popover.tsx`

**Review by pomfrida — CHANGES_REQUESTED** [review]
See comments

File: libraries/core-react/src/Divider/Divider.tsx [hunk 5]
```diff
@@ -17,25 +17,25 @@ const StyledDivider = styled.hr<StyleProps>`
   height: ${(props) => props.dividerHeight};
 `
 
-type Props = {
-  /** Color variants
- @default medium */
+export type DividerProps = {
```
Comment (mimarz) [inline libraries/core-react/src/Divider/Divider.tsx:20]: Is there a specific reason you renamed from `Props` to `DividerProps`? We have been using `Props` naming on all components for the "main" component properties.

**Review by mimarz — CHANGES_REQUESTED** [review]
Suggest updating your branch with changes from #729 to avoid errors with removal of `displayName` and simplification.

Can we not use `Eds` prefix for our components also? Feels wrong to just use `Button` or `Divider` as it might clash with other stuff, or harder to debug.

File: libraries/core-react/src/Divider/Divider.tsx [hunk 6]
```diff
@@ -17,25 +17,25 @@ const StyledDivider = styled.hr<StyleProps>`
...
-  const styleProps = {
-    backgroundColor: tokens.color[color],
-    marginTop: tokens[variant].spacings.top,
-    marginBottom: tokens[variant].spacings.bottom,
-    dividerHeight: tokens.height,
-  }
-  return <StyledDivider {...styleProps} className={className} ref={ref} />
-})
+export const Divider = forwardRef<HTMLHRElement, DividerProps>(
+  ({ color = 'medium', variant = 'medium', className = '' }, ref) => {
```
Comment (mimarz) [inline libraries/core-react/src/Divider/Divider.tsx:30]: This is an anonymous function, maybe thats why you eslint complains when you remove manual definition of `displayName`?

File: libraries/core-react/src/Popover/PopoverAnchor.tsx (hunk 4 above)
Comment (vnys) [reply libraries/core-react/src/Popover/PopoverAnchor.tsx:15]: The generated displayName will be `PopoverAnchor` so I changed the checking to `popoverChildren.type.displayName === 'PopoverAnchor'` in `Popover.tsx`.

File: apps/storybook-react/stories/Divider.stories.tsx [hunk 7]
```diff
@@ -0,0 +1,48 @@
+import React, { FunctionComponent } from 'react'
```
[the remark this answers is not in the document]
Comment (vnys) [reply apps/storybook-react/stories/Divider.stories.tsx]: Fixed

File: libraries/core-react/src/Divider/Divider.tsx (hunk 5 above)
Comment (vnys) [reply libraries/core-react/src/Divider/Divider.tsx:20]: We have to export the types to use them in the stories. I forgot that yesterday, so it wasn’t that clear, but take a look at [the story](https://github.com/equinor/design-system/blob/020ce6cacb4366333843d787a1256ef352fc2526/apps/storybook-react/stories/Divider.stories.tsx#L32) where the props are being used, and also index.ts where [the props are exported](https://github.com/equinor/design-system/blob/020ce6cacb4366333843d787a1256ef352fc2526/libraries/core-react/src/index.ts#L5). If we have several components in the same story it’s better to have individual names. Exporting the props like that is removed from the bundle, but something we need to do when we use the typescript files directly in the Storybook.

File: libraries/core-react/src/Divider/Divider.tsx (hunk 6 above)
Comment (vnys) [reply libraries/core-react/src/Divider/Divider.tsx:30]: Could be, I’ll look into that

**Comment by vnys** [comment]
> Can we not use `Eds` prefix for our components also? Feels wrong to just use `Button` or `Divider` as it might clash with other stuff, or harder to debug.

That’s a bigger debate which I don’t think should hold back this pr. But I have deliberately commented out instead of removing the `displayNames` for a reason, in case we find other ways to fix this.

**Comment by vnys** [comment]
> Suggest updating your branch with changes from #729 to avoid errors with removal of `displayName` and simplification.

Will do

File: libraries/core-react/src/Divider/Divider.tsx (hunk 6 above)
Comment (vnys) [reply libraries/core-react/src/Divider/Divider.tsx:30]: It is indeed because it’s an arrow function. Normally javascript infers the function name from the variable that holds the arrow function, but in this case that does not work. So then we either have to refactor the components that use arrow functions, or just accept that we have to explicitly declare the `displayName` in these cases.

**Review by pomfrida — APPROVED** [review]
LGTM 👍

**Review by wenche — APPROVED** [review]
Looks good as a starting point for the rest of the work 👍

File: libraries/core-react/src/Divider/Divider.tsx (hunk 6 above)
Comment (mimarz) [reply libraries/core-react/src/Divider/Divider.tsx:30]: Should be no problem to change it from arrow function to named function in most cases tho. Suggest we conform on on way of doing this and change our components using arrow functions to named functions then?

File: libraries/core-react/src/Divider/Divider.tsx (hunk 5 above)
Comment (mimarz) [reply libraries/core-react/src/Divider/Divider.tsx:20]: So either we call the explicitly, which means we need to change all existing components `Props` or we can just rename it when importing in the stories. Which do we favour? 🤔

File: libraries/core-react/src/Divider/Divider.tsx (hunk 6 above)
Comment (vnys) [reply libraries/core-react/src/Divider/Divider.tsx:30]: Yes, I agree. I made an issue (#732)

**Review by mimarz — APPROVED** [review]
Looks good, but there are some actions points we need to figure out for code uniformity from this 😅  "DividerProps" is already diverging from all our other components

* What do we call our component "props" type?
* How do we name our functions for `displayName`? Prefix or no prefix etc.
* Change arrow function components to named functions?

File: libraries/core-react/src/Divider/Divider.tsx (hunk 5 above)
Comment (wenche) [reply libraries/core-react/src/Divider/Divider.tsx:20]: I can live with both approaches 🤷‍♀️  Initially I thought that it will be OK to rename imports as most of the components (?) only have one single component, but when I browsed the mighty Internet to see what other people do they often write <Component>Props, including the Storybook docs. So it might be a defacto standard?

Comment (vnys) [reply libraries/core-react/src/Divider/Divider.tsx:20]: Yes, I’ve seen that too…
