### PR TITLE
♻️ Clean redundant code for btn in Search

### LINKED ISSUE #1737: Search clear button
The "clear button" in our `Search` component is not a button and thus fails a11y. Should be updated to use the `Button` so its focusable and readable.

### PR DESCRIPTION
**Pull request by laliq**
resolves #1737

In Search.tokens `button` entity was created,  with defined height, width and spacing.

In Search component:
* `Button` component was imported. 
* New `button` entity was added.

### CODE REVIEW

File: libraries/core-react/src/components/Search/Search.tsx [hunk 1]
```diff
@@ -307,8 +279,14 @@ export const Search = forwardRef<HTMLInputElement, SearchProps>(function Search(
...
       <Icon data={search} aria-hidden size={size} />
       <Input {...inputProps} />
-      <InsideButton {...clearButtonProps} aria-label="Clear search">
-        <Icon data={close} size={size} />
+      <InsideButton
+        {...clearButtonProps}
+        aria-label={'clear search'}
+        title="clear"
+        variant="ghost_icon"
+        type="button"
```
Comment (mimarz) [inline libraries/core-react/src/components/Search/Search.tsx:287]: Since we are using an actual `button` now, this type is redundant.

File: libraries/core-react/src/components/Search/Search.tsx [hunk 2]
```diff
@@ -294,7 +267,6 @@ export const Search = forwardRef<HTMLInputElement, SearchProps>(function Search(
   const clearButtonProps = {
     isActive: state.isActive,
     size,
```
Comment (mimarz) [inline libraries/core-react/src/components/Search/Search.tsx:269]: Suggest removing `size` property as `Button` does not support it nor, our styled wrapper.

**Review by mimarz — CHANGES_REQUESTED** [review]
Some suggestions on cleaning up redundant variables/properties now that we use a `Button`.

**Review by mimarz — APPROVED** [review]
LGTM 👍
