### PR TITLE
🐛♻️ Replacing ul>li with div>button fixes keyboard enter-as-click

### LINKED ISSUE #1702: MenuItem does not active on Enter keypress
When testing the `Menu` component with keyboard navigation, the selected menu item did not close or active on keypress. This is in violation of how expected behaviour for menu should be according to [aria best practices](https://www.w3.org/TR/wai-aria-practices-1.1/#menu)

### PR DESCRIPTION
**Pull request by oddvernes**
resolves #1702 

In the menu, we want keyboard 'enter' to behave the same as clicking an item with the mouse. By replacing the `li` element with a `button` element we get this `onClick` behaviour with keyboard for free

### CODE REVIEW

File: libraries/core-react/src/components/Menu/MenuSection.tsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ import { spacingsTemplate } from '../../utils'
 import { Divider } from '../Divider'
 import { Typography } from '../Typography'
 
-const ListItem = styled.li.attrs(() => ({
+const ListItem = styled.div.attrs(() => ({
```
Comment (mimarz) [inline libraries/core-react/src/components/Menu/MenuSection.tsx:9]: Suggest changing this to `Title` or `Header` something more descriptive as its a container for section name

File: libraries/core-react/src/components/Menu/MenuItem.tsx [hunk 2]
```diff
@@ -124,7 +127,7 @@ export const MenuItem = memo(
     return (
       <ListItem
         {...props}
-        ref={useCombinedRefs<HTMLLIElement>(ref, (el) => {
+        ref={useCombinedRefs<HTMLButtonElement>(ref, (el) => {
           if (el !== null && isFocused) {
             el.focus()
           }
```
Comment (mimarz) [inline libraries/core-react/src/components/Menu/MenuItem.tsx:133]: Do we still need the `!disabled` check on line 137 now that its a `button`  element, the onClick handler should not be triggered when disabled.

**Review by mimarz — CHANGES_REQUESTED** [review]
Looks good! 👍 

Just some small naming and cleanup now that its button!
Did you check a11y semantic rules for changing `ul>li` to `div>button` (all I could find was that roles `menu`, `menuitem`, `aria-expanded` etc needed to be assigned)?

**Comment by oddvernes** [comment]
> Did you check a11y semantic rules for changing ul>li to div>button (all I could find was that roles menu, menuitem, aria-expanded etc needed to be assigned)?

The roles menu and menuitem are already assigned so I don't think there is anything else needed. I can try with screenreader on the new and old solution later to see if there is a difference

File: libraries/core-react/src/components/Menu/MenuSection.tsx (hunk 1 above)
Comment (oddvernes) [reply libraries/core-react/src/components/Menu/MenuSection.tsx]: agreed, done 👍

File: libraries/core-react/src/components/Menu/MenuItem.tsx (hunk 2 above)
Comment (oddvernes) [reply libraries/core-react/src/components/Menu/MenuItem.tsx:133]: Good point, we did not need it

File: libraries/core-react/src/components/Menu/MenuItem.tsx [hunk 3]
```diff
@@ -28,10 +28,12 @@ type StyleAttrsProps = {
   isFocused: string
 }
 
-const ListItem = styled.li.attrs<StyleAttrsProps>(({ isFocused }) => ({
+const ListItem = styled.button.attrs<StyleAttrsProps>(({ isFocused }) => ({
```
Comment (mimarz) [inline libraries/core-react/src/components/Menu/MenuItem.tsx:31]: Rename to `Item`?

**Review by mimarz — APPROVED** [review]
LGTM 👍

File: libraries/core-react/src/components/Menu/MenuItem.tsx (hunk 3 above)
Comment (oddvernes) [reply libraries/core-react/src/components/Menu/MenuItem.tsx]: Sure!
