### PR TITLE
🐛 Cell, DataCell: fix deprecated DOM intefrace

### LINKED ISSUE #1739: DOM interface changes for Table
`HTMLTableDataCellElement` deprecated, preferred `HTMLTableCellElement`
`HTMLTableHeaderCellElement` deprecated, preferred `HTMLTableCellElement`

### PR DESCRIPTION
**Pull request by laliq**
resolves #1739 

`HTMLTableDataCellElement` and `HTMLTableHeaderCellElement` are deprecated.
According to MDN docs. the new DOM interface is `HTMLTableCellElement`, for manipulating the layout and presentation of table cells, either header or data cells, in an HTML document.

### CODE REVIEW

File: libraries/core-react/src/components/Table/Cell.tsx [hunk 1]
```diff
@@ -12,11 +12,11 @@ export type CellProps = {
...
   sort?: React.AriaAttributes['aria-sort']
 } & (
-  | TdHTMLAttributes<HTMLTableDataCellElement>
-  | ThHTMLAttributes<HTMLTableHeaderCellElement>
+  | TdHTMLAttributes<HTMLTableCellElement>
+  | ThHTMLAttributes<HTMLTableCellElement>
 )
 export const Cell = forwardRef<
-  HTMLTableDataCellElement | HTMLTableHeaderCellElement,
+  HTMLTableCellElement | HTMLTableCellElement,
```
Comment (mimarz) [inline libraries/core-react/src/components/Table/Cell.tsx:19]: The "or" is now redundant here when types are the same.

**Review by mimarz — CHANGES_REQUESTED** [review]
I think you might have missed one fix in `HeaderCell.tsx`? 😅

**Review by mimarz — APPROVED** [review]
LGTM 👍
