### PR TITLE
Chips should only have hover on onClick events

### LINKED ISSUE #2994: Chips has a hover effect when no click action exists
**Describe the bug**

When there is no onClick event on the Chip there is still is a hover effect indicating there should/could be an action
**Steps to reproduce the bug**

1. Add a Chip without onClick behaviour
2. Hover the mouse over the element
3. nod

**Expected behavior**
Nothing should happen on hover when no click behaviour exists

### PR DESCRIPTION
**Pull request by bjartebore**
resolves #2994

### CODE REVIEW

File: packages/eds-core-react/src/components/Chip/Chip.tsx [hunk 1]
```diff
@@ -45,16 +45,18 @@ const StyledChips = styled.div.attrs<StyleProps>(
     fill: ${typography.color};
   }
 
-  @media (hover: hover) and (pointer: fine) {
-    &:hover {
-      color: ${states.hover.typography.color};
+  ${({ clickable }) => clickable && css`
```
Comment (oddvernes) [inline packages/eds-core-react/src/components/Chip/Chip.tsx:48]: I see there is already a clickable check a little further down on line 70-something that only adds corsor, would it be possible to add the color and fill there instead so its in one place? also the error state has its own hover color even further down that is not checked for clickable

**Review by oddvernes — CHANGES_REQUESTED** [review]

File: packages/eds-core-react/src/components/Chip/Chip.tsx (hunk 1 above)
Comment (bjartebore) [reply packages/eds-core-react/src/components/Chip/Chip.tsx:48]: ofc, and I am a little embarrassed that I did not see it myself

**Review by oddvernes — APPROVED** [review]
LGTM
