### PR TITLE
fix: resolve runtime errors in Autocomplete and DatePicker

### LINKED ISSUE #4619: Autocomplete and Datepicker components giving errors
#### General objective

Ensure that the Autocomplete and Datepicker components function correctly without errors, and integrate seamlessly with Formik, matching the behavior demonstrated in the Storybook examples.

#### Specific objectives

- Integrate the Autocomplete component with Formik so that it behaves exactly as shown in the Storybook demo.
- Integrate the Datepicker component with Formik with full functionality and expected UI/UX behavior from the Storybook demo.
- Resolve existing errors occurring when these components are used within forms.

#### Outcome

Both Autocomplete and Datepicker components should be fully compatible with Formik and operate identically to their Storybook implementations, with no errors or unexpected behavior.

#### Owner

sht@equinor.com, virai@equinor.com, team Co-lab.

Image

Image

### PR DESCRIPTION
**Pull request by pomfrida**
## Summary
Fixes #4619

- **Popover/DatePicker**: Wrap `showPopover()`/`hidePopover()` in try-catch to handle timing issue where the native Popover API is called before React applies the `popover="manual"` attribute
- **Autocomplete**: Same try-catch fix for the dropdown's popover toggle
- **AutocompleteContext**: Replace React 19-only `use()` with `useContext()` for React 18 compatibility

## Test plan
- [x] Existing Popover, Autocomplete, and DatePicker tests pass (64/64)
- [x] Lint passes
- [ ] Verify in Storybook: Popover, Autocomplete dropdown, and DatePicker calendar open/close correctly

### CODE REVIEW

File: packages/eds-core-react/src/components/Popover/Popover.tsx [hunk 1]
```diff
@@ -167,12 +167,14 @@ export const Popover = forwardRef<HTMLDivElement, PopoverProps>(
 
     useEffect(() => {
       if (!elements.floating) return
-      if (open) {
-        if (elements.floating.isConnected) {
```
Comment (Chibuzor-Nwemambu) [inline packages/eds-core-react/src/components/Popover/Popover.tsx:171]: Any particular reason why the `isConnected` was dropped? I think it is an effective guard as well. Consider including it in the try-catch

**Review by Chibuzor-Nwemambu — APPROVED** [review]
Well Done @pomfrida ✅ 🔥 

I have added a comment, but more of a consideration than a requested change.

File: packages/eds-core-react/src/components/Popover/Popover.tsx (hunk 1 above)
Comment (pomfrida) [reply packages/eds-core-react/src/components/Popover/Popover.tsx:171]: This was a mistake so good catch @Chibuzor-Nwemambu 💯
