### PR TITLE
💄 Search: Override Chrome autofill background

### LINKED ISSUE #2138: Search component AutoComplete blue color
**Describe the bug**

When you use autoComplete on the Search component it has this blue color added that does not look good.

**Steps to reproduce the bug**

1. Go to https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-search--default
2. Select an auto-complete value if you have any
3. Looks like the image below

image

**Expected behavior**

To not have this blue color

**Specifications**

- Version: 0.18.0
- Browser: Chrome
- OS: Windows

**Additional context**

Screenshot (19)

### PR DESCRIPTION
**Pull request by oddvernes**
resolves #2138

### CODE REVIEW

File: packages/eds-core-react/src/components/Search/Search.tsx [hunk 1]
```diff
@@ -117,6 +117,12 @@ const SearchInput = styled(Input)(({ theme, disabled }) => {
     &:focus {
       outline: none;
     }
+    &:-webkit-autofill {
```
Comment (mimarz) [inline packages/eds-core-react/src/components/Search/Search.tsx:120]: Did it work without the vendor prefix? I thingk `styled-components` has built in autoprefixer 🤔

Comment (oddvernes) [reply packages/eds-core-react/src/components/Search/Search.tsx:120]: It does not. The non-prefixed alone does not work, and does not get autoprefixed, so this is more of a future-proofing (css-tricks recommmended including it)

**Review by mimarz — APPROVED** [review]
LGTM 👍
