### PR TITLE
Fix file upload and link buttons

### LINKED ISSUE #482: File upload and link buttons don’t look right
**Describe the bug**

After introducing the span-element to fix the Safari bug in #465 – the upload and link buttons don’t look right

**Steps to reproduce the bug**

1. See the [link button in the storybook](https://eds-storybook-react.azurewebsites.net/iframe.html?id=components-button--link&viewMode=story)
2. See the [upload button in the storybook](https://eds-storybook-react-development.azurewebsites.net/iframe.html?id=components-button--file-upload&viewMode=story)
3. Shake your head in disbelief

**Expected behavior**

The buttons should look like they used to before the bug fix

**Specifications**

- Version: 0.5.1
- Browser: Edge
- OS: MacOS

**Additional context**

**File upload**

image

**Link**

image

### PR DESCRIPTION
**Pull request by vnys**
resolves #482

### CODE REVIEW

File: libraries/core-react/src/Button/Button.jsx [hunk 1]
```diff
@@ -13,6 +13,7 @@ const ButtonInner = styled.span`
   grid-gap: 8px;
   grid-auto-flow: column;
   align-items: center;
+  height: 100%;
```
Comment (vnys) [inline libraries/core-react/src/Button/Button.jsx:16]: fixes vertical alignment bug in link button

File: libraries/core-react/src/Button/Button.jsx [hunk 2]
```diff
@@ -94,6 +95,7 @@ const ButtonBase = styled.button`
   text-decoration: none;
   position: relative;
   cursor: pointer;
+  display: inline-block;
```
Comment (vnys) [inline libraries/core-react/src/Button/Button.jsx:98]: overrides default display type when sending in an inline tag in the as-prop.
